name: Run Selenium Tests with Allure

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Allure CLI
      run: |
        sudo apt-add-repository ppa:qameta/allure
        sudo apt-get update
        sudo apt-get install allure

    - name: Start Xvfb (virtual display for Selenium)
      run: |
        sudo apt-get install xvfb
        Xvfb :99 &
        export DISPLAY=:99

    - name: Run tests with Allure
      run: |
        export DISPLAY=:99
        pytest tests --alluredir=allure-results -v | tee pytest-log.txt

    - name: Generate Allure Report (if results exist)
      run: |
        if [ -d "allure-results" ] && [ "$(ls -A allure-results)" ]; then
          allure generate allure-results --clean -o allure-report
        else
          echo "No Allure results found, skipping report generation."
        fi

    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report

    - name: Upload Pytest Log
      uses: actions/upload-artifact@v4
      with:
        name: pytest-log
        path: pytest-log.txt
